### ISSUE TITLE
Docker Build Failing

### ISSUE THREAD

**Issue by Frank-P-Lu** [microsoft/QuantumKatas#895]
Hi there,
I'm having an issue running `docker build -t katas .` on line 31 of the dockerfile.

```
ERROR: failed to solve: process "/bin/sh -c cd ${HOME}/ &&     for solution in $(find . -type f -name \"*.sln\"); do dotnet restore \"$solution\"; done &&     ./scripts/prebuild-kata.sh BasicGates &&     ./scripts/prebuild-kata.sh CHSHGame &&     ./scripts/prebuild-kata.sh DeutschJozsaAlgorithm &&     ./scripts/prebuild-kata.sh GroversAlgorithm &&     ./scripts/prebuild-kata.sh Measurements &&     ./scripts/prebuild-kata.sh QFT &&     ./scripts/prebuild-kata.sh Superposition &&     ./scripts/prebuild-kata.sh Teleportation &&     ./scripts/prebuild-kata.sh tutorials/ComplexArithmetic ComplexArithmetic.ipynb &&     ./scripts/prebuild-kata.sh tutorials/ExploringDeutschJozsaAlgorithm DeutschJozsaAlgorithmTutorial_P1.ipynb &&     ./scripts/prebuild-kata.sh tutorials/ExploringGroversAlgorithm ExploringGroversAlgorithmTutorial.ipynb &&     ./scripts/prebuild-kata.sh tutorials/LinearAlgebra LinearAlgebra.ipynb &&     ./scripts/prebuild-kata.sh tutorials/MultiQubitGates MultiQubitGates.ipynb &&     ./scripts/prebuild-kata.sh tutorials/MultiQubitSystems MultiQubitSystems.ipynb &&     ./scripts/prebuild-kata.sh tutorials/MultiQubitSystemMeasurements MultiQubitSystemMeasurements.ipynb &&     ./scripts/prebuild-kata.sh tutorials/Qubit Qubit.ipynb &&     ./scripts/prebuild-kata.sh tutorials/RandomNumberGeneration RandomNumberGenerationTutorial.ipynb &&     ./scripts/prebuild-kata.sh tutorials/SingleQubitGates SingleQubitGates.ipynb &&     ./scripts/prebuild-kata.sh tutorials/SingleQubitSystemMeasurements SingleQubitSystemMeasurements.ipynb &&     rm ${HOME}/NuGet.config &&     echo \"<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?>          <configuration>              <packageSources>                   <clear />              </packageSources>          </configuration>    \" > ${HOME}/.nuget/NuGet/NuGet.Config" did not complete successfully: exit code: 1
```

I have attached some more of the stack trace below. 

```
 [5/6] RUN cd /home/jovyan/ &&     for solution in $(find . -type f -name "*.sln"); do dotnet restore "$solution"; done &&     ./scripts/prebuild-kata.sh BasicGates &&     ./scripts/prebuild-kata.sh CHSHGame &&     ./scripts/prebuild-kata.sh DeutschJozsaAlgorithm &&     ./scripts/prebuild-kata.sh GroversAlgorithm &&     ./scripts/prebuild-kata.sh Measurements &&     ./scripts/prebuild-kata.sh QFT &&     ./scripts/prebuild-kata.sh Superposition &&     ./scripts/prebuild-kata.sh Teleportation &&     ./scripts/prebuild-kata.sh tutorials/ComplexArithmetic ComplexArithmetic.ipynb &&     ./scripts/prebuild-kata.sh tutorials/ExploringDeutschJozsaAlgorithm DeutschJozsaAlgorithmTutorial_P1.ipynb &&     ./scripts/prebuild-kata.sh tutorials/ExploringGroversAlgorithm ExploringGroversAlgorithmTutorial.ipynb &&     ./scripts/prebuild-kata.sh tutorials/LinearAlgebra LinearAlgebra.ipynb &&     ./scripts/prebuild-kata.sh tutorials/MultiQubitGates MultiQubitGates.ipynb &&     ./scripts/prebuild-kata.sh tutorials/MultiQubitSystems MultiQubitSystems.ipynb &&     ./scripts/prebuild-kata.sh tutorials/MultiQubitSystemMeasurements MultiQubitSystemMeasurements.ipynb &&     ./scripts/prebuild-kata.sh tutorials/Qubit Qubit.ipynb &&     ./scripts/prebuild-kata.sh tutorials/RandomNumberGeneration RandomNumberGenerationTutorial.ipynb &&     ./scripts/prebuild-kata.sh tutorials/SingleQubitGates SingleQubitGates.ipynb &&     ./scripts/prebuild-kata.sh tutorials/SingleQubitSystemMeasurements SingleQubitSystemMeasurements.ipynb &&     rm /home/jovyan/NuGet.config &&     echo "<?xml version="1.0" encoding="utf-8"?>          <configuration>              <packageSources>                   <clear />              </packageSources>          </configuration>    " > /home/jovyan/.nuget/NuGet/NuGet.Config:
6.096   Determining projects to restore...
23.85   Restored /home/jovyan/tutorials/VisualizationTools/VisualizationTools.csproj (in 15.47 sec).
33.19   Restored /home/jovyan/tutorials/VisualizationTools/VisualizationTools.csproj (in 24.91 sec).
38.38   Determining projects to restore...
44.55   Restored /home/jovyan/tutorials/SingleQubitGates/SingleQubitGates.csproj (in 3.85 sec).
44.57   1 of 2 projects are up-to-date for restore.
49.73   Determining projects to restore...
55.69   Restored /home/jovyan/tutorials/Oracles/Oracles.csproj (in 3.67 sec).
55.71   1 of 2 projects are up-to-date for restore.
60.76   Determining projects to restore...
66.89   Restored /home/jovyan/tutorials/MultiQubitGates/MultiQubitGates.csproj (in 3.81 sec).
66.91   1 of 2 projects are up-to-date for restore.
71.93   Determining projects to restore...
77.95   Restored /home/jovyan/tutorials/MultiQubitSystems/MultiQubitSystems.csproj (in 3.76 sec).
77.97   1 of 2 projects are up-to-date for restore.
83.07   Determining projects to restore...
89.14   Restored /home/jovyan/tutorials/ExploringGroversAlgorithm/ExploringGroversAlgorithmTutorial.csproj (in 3.74 sec).
89.16   1 of 2 projects are up-to-date for restore.
94.30   Determining projects to restore...
100.4   Restored /home/jovyan/tutorials/ExploringDeutschJozsaAlgorithm/DeutschJozsaAlgorithmTutorial.csproj (in 3.81 sec).
100.4   1 of 2 projects are up-to-date for restore.
105.5   Determining projects to restore...
111.5   Restored /home/jovyan/tutorials/MultiQubitSystemMeasurements/MultiQubitSystemMeasurements.csproj (in 3.72 sec).
111.5   1 of 2 projects are up-to-date for restore.
116.6   Determining projects to restore...
122.8   Restored /home/jovyan/tutorials/QuantumClassification/QuantumClassification.csproj (in 3.97 sec).
127.9   Determining projects to restore...
134.0   Restored /home/jovyan/tutorials/RandomNumberGeneration/RandomNumberGenerationTutorial.csproj (in 3.81 sec).
134.0   1 of 2 projects are up-to-date for restore.
139.1   Determining projects to restore...
145.3   Restored /home/jovyan/tutorials/SingleQubitSystemMeasurements/SingleQubitSystemMeasurements.csproj (in 3.99 sec).
145.4   1 of 2 projects are up-to-date for restore.
150.5   Determining projects to restore...
156.5   Restored /home/jovyan/BoundedKnapsack/BoundedKnapsack.csproj (in 3.66 sec).
156.6   1 of 2 projects are up-to-date for restore.
164.0   Determining projects to restore...
177.1   Restored /home/jovyan/utilities/DumpUnitary/DumpUnitary.csproj (in 9.58 sec).
189.6   Restored /home/jovyan/utilities/DumpUnitaryTest/DumpUnitaryTest.csproj (in 22.1 sec).
197.1   Determining projects to restore...
203.4   Restored /home/jovyan/utilities/Common/Common.csproj (in 3.17 sec).
209.3   Restored /home/jovyan/utilities/CounterSimulatorTests/CounterSimulatorTests.csproj (in 9.12 sec).
220.9   Restored /home/jovyan/utilities/Microsoft.Quantum.Katas/Microsoft.Quantum.Katas.csproj (in 20.71 sec).
220.9   1 of 4 projects are up-to-date for restore.
226.2   Determining projects to restore...
232.2   Restored /home/jovyan/MagicSquareGame/MagicSquareGame.csproj (in 3.65 sec).
232.2   1 of 2 projects are up-to-date for restore.
237.4   Determining projects to restore...
243.5   Restored /home/jovyan/KeyDistribution_BB84/KeyDistribution_BB84.csproj (in 3.8 sec).
243.5   1 of 2 projects are up-to-date for restore.
248.6   Determining projects to restore...
254.7   Restored /home/jovyan/SuperdenseCoding/SuperdenseCoding.csproj (in 3.82 sec).
254.8   1 of 2 projects are up-to-date for restore.
259.9   Determining projects to restore...
266.1   Restored /home/jovyan/SimonsAlgorithm/SimonsAlgorithm.csproj (in 3.92 sec).
266.1   1 of 2 projects are up-to-date for restore.
271.3   Determining projects to restore...
277.3   Restored /home/jovyan/PhaseEstimation/PhaseEstimation.csproj (in 3.66 sec).
277.3   1 of 2 projects are up-to-date for restore.
282.5   Determining projects to restore...
288.4   Restored /home/jovyan/DistinguishUnitaries/DistinguishUnitaries.csproj (in 3.65 sec).
288.4   1 of 2 projects are up-to-date for restore.
293.5   Determining projects to restore...
299.6   Restored /home/jovyan/UnitaryPatterns/UnitaryPatterns.csproj (in 3.78 sec).
299.6   1 of 2 projects are up-to-date for restore.
304.7   Determining projects to restore...
310.7   Restored /home/jovyan/SolveSATWithGrover/SolveSATWithGrover.csproj (in 3.81 sec).
310.8   1 of 2 projects are up-to-date for restore.
315.8   Determining projects to restore...
321.7   Restored /home/jovyan/RippleCarryAdder/RippleCarryAdder.csproj (in 3.72 sec).
326.9   Determining projects to restore...
332.9   Restored /home/jovyan/GHZGame/GHZGame.csproj (in 3.72 sec).
332.9   1 of 2 projects are up-to-date for restore.
337.9   Determining projects to restore...
344.0   Restored /home/jovyan/Teleportation/Teleportation.csproj (in 3.76 sec).
344.0   1 of 2 projects are up-to-date for restore.
349.0   Determining projects to restore...
355.2   Restored /home/jovyan/BasicGates/BasicGates.csproj (in 3.93 sec).
355.2   1 of 2 projects are up-to-date for restore.
360.3   Determining projects to restore...
366.4   Restored /home/jovyan/GraphColoring/GraphColoring.csproj (in 3.82 sec).
366.4   1 of 2 projects are up-to-date for restore.
371.5   Determining projects to restore...
377.5   Restored /home/jovyan/MarkingOracles/MarkingOracles.csproj (in 3.7 sec).
377.5   1 of 2 projects are up-to-date for restore.
382.6   Determining projects to restore...
388.6   Restored /home/jovyan/JointMeasurements/JointMeasurements.csproj (in 3.74 sec).
388.6   1 of 2 projects are up-to-date for restore.
393.7   Determining projects to restore...
399.8   Restored /home/jovyan/TruthTables/TruthTables.csproj (in 3.73 sec).
399.8   1 of 2 projects are up-to-date for restore.
404.8   Determining projects to restore...
410.8   Restored /home/jovyan/QEC_BitFlipCode/QEC_BitFlipCode.csproj (in 3.77 sec).
415.9   Determining projects to restore...
422.0   Restored /home/jovyan/DeutschJozsaAlgorithm/DeutschJozsaAlgorithm.csproj (in 3.84 sec).
422.0   1 of 2 projects are up-to-date for restore.
427.1   Determining projects to restore...
433.3   Restored /home/jovyan/GroversAlgorithm/GroversAlgorithm.csproj (in 3.91 sec).
433.3   1 of 2 projects are up-to-date for restore.
438.4   Determining projects to restore...
444.5   Restored /home/jovyan/QFT/QFT.csproj (in 3.78 sec).
444.5   1 of 2 projects are up-to-date for restore.
449.6   Determining projects to restore...
455.6   Restored /home/jovyan/Superposition/Superposition.csproj (in 3.6 sec).
455.6   1 of 2 projects are up-to-date for restore.
460.7   Determining projects to restore...
466.7   Restored /home/jovyan/CHSHGame/CHSHGame.csproj (in 3.67 sec).
466.7   1 of 2 projects are up-to-date for restore.
471.8   Determining projects to restore...
477.9   Restored /home/jovyan/Measurements/Measurements.csproj (in 3.77 sec).
477.9   1 of 2 projects are up-to-date for restore.
478.1 Prebuilding: BasicGates.ipynb in BasicGates kata...
485.2 [NbConvertApp] Converting notebook BasicGates/BasicGates.ipynb to markdown
623.3 [NbConvertApp] ERROR | Timeout waiting for execute reply (120s).
623.6 Traceback (most recent call last):
623.6   File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 778, in _async_poll_for_reply
623.6     msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
623.6   File "/usr/local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
623.6     result = await obj
623.6   File "/usr/local/lib/python3.9/site-packages/jupyter_client/channels.py", line 315, in get_msg
623.6     raise Empty
623.6 _queue.Empty
623.6 
623.6 During handling of the above exception, another exception occurred:
623.6 
623.6 Traceback (most recent call last):
623.6   File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
623.6     sys.exit(main())
623.6   File "/usr/local/lib/python3.9/site-packages/jupyter_core/application.py", line 285, in launch_instance
623.6     return super().launch_instance(argv=argv, **kwargs)
623.6   File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 1046, in launch_instance
623.6     app.start()
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 410, in start
623.6     self.convert_notebooks()
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 585, in convert_notebooks
623.6     self.convert_single_notebook(notebook_filename)
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 551, in convert_single_notebook
623.6     output, resources = self.export_single_notebook(
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 477, in export_single_notebook
623.6     output, resources = self.exporter.from_filename(
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 389, in from_filename
623.6     return super().from_filename(filename, resources, **kw)  # type:ignore
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
623.6     return self.from_file(f, resources=resources, **kw)
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 395, in from_file
623.6     return super().from_file(file_stream, resources, **kw)  # type:ignore
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
623.6     return self.from_notebook_node(
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 411, in from_notebook_node
623.6     nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
623.6     nb_copy, resources = self._preprocess(nb_copy, resources)
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 352, in _preprocess
623.6     nbc, resc = preprocessor(nbc, resc)
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 48, in __call__
623.6     return self.preprocess(nb, resources)
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 100, in preprocess
623.6     self.preprocess_cell(cell, resources, index)
623.6   File "/usr/local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 121, in preprocess_cell
623.6     cell = self.execute_cell(cell, index, store_history=True)
623.6   File "/usr/local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
623.6     return loop.run_until_complete(inner)
623.6   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
623.6     return future.result()
623.6   File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1001, in async_execute_cell
623.6     exec_reply = await self.task_poll_for_reply
623.6   File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 802, in _async_poll_for_reply
623.6     error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
623.6   File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 852, in _async_handle_timeout
623.6     raise CellTimeoutError.error_from_timeout_and_cell(
623.6 nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 120 seconds.
623.6 The message was: Cell execution timed out.
623.6 Here is a preview of the cell contents:
623.6 -------------------
623.6 %kata T101_StateFlip 
623.6 
623.6 operation StateFlip (q : Qubit) : Unit is Adj+Ctl {
623.6     // The Pauli X gate will change the |0⟩ state to the |1⟩ state and vice versa.
623.6     // Type X(q);
623.6     // Then run the cell using Ctrl+Enter (⌘+Enter on macOS).
623.6 
623.6     // ...
623.6 }
623.6 -------------------
623.6 
```

**Comment by bharambetejas** [comment]
@Frank-P-Lu Did you figure out any solution to this issue? I experienced this problem recently
